import { JournalEntry, UserProfile } from "./types";

export const MOCK_USER: UserProfile = {
  name: "小葵",
  avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=200&auto=format&fit=crop",
  bio: "今天也很好，慢慢记录生活。",
};

export const INITIAL_ENTRIES: JournalEntry[] = [
  {
    id: "2026-06-18",
    date: "2026-06-18",
    dayOfWeek: "Thu",
    dayOfMonth: 18,
    mood: "😌",
    moodText: "舒心平静",
    foodText: "和风蔬菜煎饼",
    foodRating: 4,
    foodSubtext: "脆脆焦焦，刚好填满午后。",
    foodImage: "https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?q=80&w=300&auto=format&fit=crop",
    drinkText: "热抹茶拿铁",
    drinkRating: 5,
    drinkSubtext: "茶香很轻，甜度正好。",
    drinkImage: "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?q=80&w=300&auto=format&fit=crop",
    outfitImages: ["https://images.unsplash.com/photo-1434389677669-e08b4cac3105?q=80&w=300&auto=format&fit=crop"],
    outfitText: "亚麻衬衫",
    outfitRating: 4,
    location: "雕刻时光咖啡馆",
    locationCity: "上海",
    locationTags: ["书香", "安静"],
    aiReflection: "今天像一张晒过太阳的便签。你认真吃饭、喝茶，也给自己留了一点安静的位置。",
    achievements: {
      completed: ["记录心情", "喝水 1500ml"],
      pending: ["睡前拉伸"],
    },
  },
  {
    id: "2026-06-19",
    date: "2026-06-19",
    dayOfWeek: "Fri",
    dayOfMonth: 19,
    mood: "😊",
    moodText: "小满足",
    foodText: "草莓抹茶千层",
    foodRating: 5,
    foodSubtext: "奶油很轻，像今天的好心情。",
    foodImage: "https://images.unsplash.com/photo-1551024601-bec78aea704b?q=80&w=300&auto=format&fit=crop",
    drinkText: "燕麦拿铁",
    drinkRating: 5,
    drinkSubtext: "温柔醇香。",
    drinkImage: "https://images.unsplash.com/photo-1541167760496-1628856ab772?q=80&w=300&auto=format&fit=crop",
    outfitImages: [],
    location: "静安公园",
    locationCity: "上海",
    locationTags: ["阳光", "散步"],
    aiReflection: "你把普通的一天过成了软软的周末预告。甜点、拿铁和风，都在替你好好充电。",
    achievements: {
      completed: ["记录饮品", "散步 3000 步", "拍下公园"],
      pending: [],
    },
  },
  {
    id: "2026-06-20",
    date: "2026-06-20",
    dayOfWeek: "Sat",
    dayOfMonth: 20,
    mood: "😐",
    moodText: "平静普通",
    foodText: "牛油果三明治",
    foodRating: 4,
    foodSubtext: "清爽，有一点踏实。",
    foodImage: "https://images.unsplash.com/photo-1541532713592-79a0317b6b77?q=80&w=300&auto=format&fit=crop",
    drinkText: "香草拿铁",
    drinkRating: 4,
    drinkSubtext: "香草味冲淡了一点疲惫。",
    drinkImage: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?q=80&w=300&auto=format&fit=crop",
    outfitImages: ["https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=300&auto=format&fit=crop"],
    outfitText: "宽松针织",
    outfitRating: 4,
    location: "公司天台",
    locationCity: "上海",
    locationTags: ["远眺", "放空"],
    aiReflection: "不是每一天都要闪闪发光。今天的你也在认真生活，这件事本身就很好。",
    achievements: {
      completed: ["完成今日小记"],
      pending: ["早睡"],
    },
  },
];

export const EMOTIONS = [
  { char: "😊", text: "开心" },
  { char: "😌", text: "舒心" },
  { char: "😐", text: "平静" },
  { char: "😔", text: "低落" },
  { char: "😵", text: "疲惫" },
];
